# Generated by Django 6.0.6 on 2026-07-02 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='MovementMotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Motivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Motivo de Movimiento',
                'verbose_name_plural': 'Motivos de Movimiento',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='TECNM', max_length=255, verbose_name='Nombre de la Institución')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logotipo Institucional')),
                ('default_min_stock', models.IntegerField(default=5, verbose_name='Stock Mínimo por Defecto')),
                ('code_prefix', models.CharField(default='INV', max_length=10, verbose_name='Prefijo de Códigos')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Abreviación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('action', models.CharField(max_length=100, verbose_name='Acción')),
                ('details', models.TextField(verbose_name='Detalles')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bitácora de Auditoría',
                'verbose_name_plural': 'Bitácoras de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.location', verbose_name='Ubicación Padre')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código Interno')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('OBS', 'Obsoleto')], default='ACT', max_length=3, verbose_name='Estado')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Directo (Solo lectura)')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='product_qrs/', verbose_name='Código QR')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='product_barcodes/', verbose_name='Código de Barras')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Categoría')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='Ubicación')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unit', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENT', 'Entrada'), ('SAL', 'Salida'), ('AJP', 'Ajuste Positivo'), ('AJN', 'Ajuste Negativo')], max_length=3, verbose_name='Tipo de Movimiento')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('related_document', models.FileField(blank=True, null=True, upload_to='movement_docs/', verbose_name='Documento Relacionado')),
                ('previous_stock', models.IntegerField(editable=False, verbose_name='Stock Anterior')),
                ('result_stock', models.IntegerField(editable=False, verbose_name='Stock Resultante')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('motive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.movementmotive', verbose_name='Motivo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
    ]
